//! Frontend attach/detach lease types. Distinct from [`super::snapshot::FrontendGeneration`].
//!
//! Track 07 implements attach/detach ack. This closeout freezes the types and
//! does not issue a lease from `try_send`.

use crate::ids::FrontendInstanceId;

/// Supervisor-owned attach generation. Not the model-display DTO.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct FrontendLeaseGeneration(u64);

impl FrontendLeaseGeneration {
    #[allow(dead_code)]
    pub(crate) fn new(value: u64) -> Self {
        Self(value)
    }

    /// Numeric generation.
    pub const fn get(self) -> u64 {
        self.0
    }
}

/// Opaque lease issued after a confirmed attach. Construction stays crate-private
/// until Track 07 implements actor ack.
#[derive(Debug)]
pub struct FrontendLease {
    frontend_id: FrontendInstanceId,
    generation: FrontendLeaseGeneration,
}

impl FrontendLease {
    #[allow(dead_code)]
    pub(crate) fn issue(
        frontend_id: FrontendInstanceId,
        generation: FrontendLeaseGeneration,
    ) -> Self {
        Self {
            frontend_id,
            generation,
        }
    }

    /// Attached frontend instance.
    pub fn frontend_id(&self) -> &FrontendInstanceId {
        &self.frontend_id
    }

    /// Lease generation issued at attach.
    pub fn generation(&self) -> FrontendLeaseGeneration {
        self.generation
    }

    #[allow(dead_code)]
    pub(crate) fn into_parts(self) -> (FrontendInstanceId, FrontendLeaseGeneration) {
        (self.frontend_id, self.generation)
    }
}

/// Supervisor lifecycle commands. Wired onto a dedicated lane in Track 07.
#[derive(Debug)]
pub enum SupervisorCommand {
    /// Register one frontend instance.
    AttachFrontend {
        /// Instance identity generated by the process supervisor.
        id: FrontendInstanceId,
    },
    /// Release a previously issued lease.
    DetachFrontend {
        /// Lease returned by a confirmed attach.
        lease: FrontendLease,
    },
    /// Supervisor-initiated shutdown.
    Shutdown {
        /// Why the supervisor is stopping the host.
        reason: String,
    },
}

/// Why a future confirmed attach failed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum AttachError {
    /// This process already holds a live lease.
    AlreadyAttached,
    /// Another frontend instance is attached.
    FrontendOccupied { current: FrontendInstanceId },
    /// The command lane is full.
    Backpressured,
    /// The command lane closed.
    Disconnected,
    /// The caller deadline elapsed before send.
    DeadlineExceeded,
    /// The service actor is gone.
    ServiceGone,
}

/// Why a future confirmed detach failed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum DetachError {
    /// The lease generation is no longer current.
    StaleLease,
    /// The control lane is full.
    Backpressured,
    /// The control lane closed.
    Disconnected,
    /// The caller deadline elapsed before send.
    DeadlineExceeded,
    /// The service actor is gone.
    ServiceGone,
}

/// Result of a successful detach.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DetachReport {
    /// Detached frontend instance.
    pub frontend_id: FrontendInstanceId,
    /// Lease generation that was detached.
    pub generation: FrontendLeaseGeneration,
    /// Confirmations denied while detaching.
    pub denied_confirmations: usize,
}
