//! Frontend attach/detach lease types. Distinct from [`super::snapshot::FrontendGeneration`].

use std::fmt;

use crate::ids::FrontendInstanceId;

/// Supervisor-owned attach generation. Not the model-display DTO.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct FrontendLeaseGeneration(u64);

impl FrontendLeaseGeneration {
    pub(crate) fn new(value: u64) -> Self {
        Self(value)
    }

    /// Numeric generation.
    pub const fn get(self) -> u64 {
        self.0
    }
}

/// Opaque lease issued after a confirmed attach. Construction stays crate-private.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FrontendLease {
    frontend_id: FrontendInstanceId,
    generation: FrontendLeaseGeneration,
}

impl FrontendLease {
    pub(crate) fn issue(
        frontend_id: FrontendInstanceId,
        generation: FrontendLeaseGeneration,
    ) -> Self {
        Self {
            frontend_id,
            generation,
        }
    }

    /// Attached frontend instance.
    pub fn frontend_id(&self) -> &FrontendInstanceId {
        &self.frontend_id
    }

    /// Lease generation issued at attach.
    pub fn generation(&self) -> FrontendLeaseGeneration {
        self.generation
    }

    pub(crate) fn into_parts(self) -> (FrontendInstanceId, FrontendLeaseGeneration) {
        (self.frontend_id, self.generation)
    }
}

/// Supervisor lifecycle commands. Reply handles stay on the private envelope.
#[derive(Debug)]
pub enum SupervisorCommand {
    /// Register one frontend instance.
    AttachFrontend {
        /// Instance identity generated by the process supervisor.
        id: FrontendInstanceId,
    },
    /// Release a previously issued lease.
    DetachFrontend {
        /// Lease returned by a confirmed attach.
        lease: FrontendLease,
    },
    /// Supervisor-initiated shutdown.
    Shutdown {
        /// Why the supervisor is stopping the host.
        reason: String,
    },
}

/// Why a future confirmed attach failed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum AttachError {
    /// This process already holds a live lease.
    AlreadyAttached,
    /// Another frontend instance is attached.
    FrontendOccupied {
        /// Instance that currently holds the lease.
        current: FrontendInstanceId,
    },
    /// The supervisor lane is full and the caller deadline has already elapsed.
    Backpressured,
    /// The supervisor lane closed.
    Disconnected,
    /// The caller deadline elapsed before send or reply.
    DeadlineExceeded,
    /// The service actor is gone.
    ServiceGone,
}

/// Why a future confirmed detach failed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum DetachError {
    /// The lease generation is no longer current.
    StaleLease,
    /// The supervisor lane is full and the caller deadline has already elapsed.
    Backpressured,
    /// The supervisor lane closed.
    Disconnected,
    /// The caller deadline elapsed before send or reply.
    DeadlineExceeded,
    /// The service actor is gone.
    ServiceGone,
}

/// Result of a successful detach.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DetachReport {
    /// Detached frontend instance.
    pub frontend_id: FrontendInstanceId,
    /// Lease generation that was detached.
    pub generation: FrontendLeaseGeneration,
    /// Confirmations denied while detaching.
    pub denied_confirmations: usize,
}

impl fmt::Display for AttachError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::AlreadyAttached => write!(f, "frontend already attached"),
            Self::FrontendOccupied { current } => {
                write!(f, "frontend occupied by {current}")
            }
            Self::Backpressured => write!(f, "frontend attach backpressured"),
            Self::Disconnected => write!(f, "frontend attach disconnected"),
            Self::DeadlineExceeded => write!(f, "frontend attach deadline exceeded"),
            Self::ServiceGone => write!(f, "service gone during attach"),
        }
    }
}

impl fmt::Display for DetachError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::StaleLease => write!(f, "stale frontend lease"),
            Self::Backpressured => write!(f, "frontend detach backpressured"),
            Self::Disconnected => write!(f, "frontend detach disconnected"),
            Self::DeadlineExceeded => write!(f, "frontend detach deadline exceeded"),
            Self::ServiceGone => write!(f, "service gone during detach"),
        }
    }
}
